remote_theme: mmistakes/minimal-mistakes@master

plugins:
- jekyll-remote-theme

title: Car Recognizer

description: An image classification API that classifies 10 different car models

author:
  name: Sk Shabaz
